CREATE TABLE IF NOT EXISTS nsw_vg_raw.land_value_row (
    district_code INT,
    district_name TEXT,
    property_id INT PRIMARY KEY,
    property_type TEXT,
    property_name TEXT,
    unit_number TEXT,
    house_number TEXT,
    street_name TEXT,
    suburb_name TEXT,
    postcode varchar(4),
    property_description TEXT,
    zone_code varchar(3) NOT NULL,
    area FLOAT,
    area_type TEXT,
    base_date_1 DATE,
    land_value_1 BIGINT,
    authority_1 TEXT,
    basis_1 TEXT,
    base_date_2 DATE,
    land_value_2 BIGINT,
    authority_2 TEXT,
    basis_2 TEXT,
    base_date_3 DATE,
    land_value_3 BIGINT,
    authority_3 TEXT,
    basis_3 TEXT,
    base_date_4 DATE,
    land_value_4 BIGINT,
    authority_4 TEXT,
    basis_4 TEXT,
    base_date_5 DATE,
    land_value_5 BIGINT,
    authority_5 TEXT,
    basis_5 TEXT,
    source_file_position INT NOT NULL,
    source_file_name TEXT NOT NULL,
    source_date DATE NOT NULL
);
